export const FETCH_POPULAR_SUBS_START = 'FETCH_POPULAR_SUBS_START';
export const FETCH_POPULAR_SUBS_SUCCESS = 'FETCH_POPULAR_SUBS_SUCCESS';
export const FETCH_POPULAR_SUBS_FAIL = 'FETCH_POPULAR_SUBS_FAIL';
