export const FETCH_POSTS_START = "FETCH_POSTS_START";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAIL = "FETCH_POSTS_FAIL";

export const FETCH_SUBINFO_START = "FETCH_SUBINFO_START";
export const FETCH_SUBINFO_SUCCESS = "FETCH_SUBINFO_SUCCESS";
export const FETCH_SUBINFO_FAIL = "FETCH_SUBINFO_FAIL";

export const FETCH_POPULAR_SUBS_START = "FETCH_POPULAR_SUBS_START";
export const FETCH_POPULAR_SUBS_SUCCESS = "FETCH_POPULAR_SUBS_SUCCESS";
export const FETCH_POPULAR_SUBS_FAIL = "FETCH_POPULAR_SUBS_FAIL";